# Generated by Django 3.2.10 on 2022-10-12 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('cedula', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('pasword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cooperative', models.CharField(max_length=255)),
                ('cedula_cafetera', models.CharField(max_length=255)),
                ('special_program', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Expreso'), ('2', 'Rainforest')], default='0', max_length=255)),
                ('login', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='coffe_manager_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type_cooffee', models.CharField(choices=[('0', 'Tipo de Cafe'), ('1', 'Estandar'), ('2', 'Regional'), ('3', 'S. Precio ML'), ('4', 'Pasilla')], default='0', max_length=255)),
                ('weight_cooffe', models.FloatField()),
                ('unit_value', models.FloatField()),
                ('overall_value', models.FloatField()),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='coffe_manager_app.user')),
            ],
        ),
    ]
